# Generated by Django 4.1.5 on 2023-01-21 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('N_INCIDENTE', models.CharField(blank=True, max_length=255, null=True)),
                ('NOMBRE_INDICENCIA', models.CharField(blank=True, max_length=100, null=True)),
                ('FECHA_SOLICITUD', models.DateField()),
                ('ESTADO', models.CharField(blank=True, choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Finalizado Correctamente', 'Finalizado Correctamente')], default='Recibido', max_length=30, null=True)),
                ('DESCRIPCION_INCIDENCIA', models.CharField(blank=True, max_length=255, null=True)),
                ('DESCRIPCION_SOLUCION', models.CharField(blank=True, max_length=255, null=True)),
                ('ULTIMA_ACTUALIZACION', models.DateField(auto_now_add=True)),
                ('COMENTARIOS', models.TextField(blank=True, null=True)),
                ('ASIGNADO_A', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.usuario')),
                ('ROBOT', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.robots')),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
            },
        ),
    ]
