# Generated by Django 4.1.5 on 2023-01-21 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_incidencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerencia',
            name='HORAS_BENEFICIO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='incidencias',
            name='ESTADO',
            field=models.CharField(blank=True, choices=[('Recibido', 'Recibido'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado')], default='Recibido', max_length=30, null=True),
        ),
    ]
