# Generated by Django 4.1.5 on 2023-02-06 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_robots_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejecucionesprocesos',
            name='SERVIDOR',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.servidores'),
        ),
    ]
