# Generated by Django 4.1.5 on 2023-02-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_monitoreo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoreo',
            options={'verbose_name': 'Monitoreo', 'verbose_name_plural': 'Monitoreos'},
        ),
    ]
