# Generated by Django 4.1.5 on 2023-02-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_monitoreo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoreo',
            name='Gerencia',
            field=models.TextField(blank=True, null=True),
        ),
    ]
