# Generated by Django 4.1.5 on 2023-02-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_monitoreo_gerencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='robots',
            old_name='INCIDENTES',
            new_name='EJECUCIONES',
        ),
        migrations.AddField(
            model_name='robots',
            name='ERRORES',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
