# Generated by Django 4.1.5 on 2023-02-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_rename_incidentes_robots_ejecuciones_robots_errores'),
    ]

    operations = [
        migrations.AddField(
            model_name='robots',
            name='FATAL',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
