# Generated by Django 4.1.5 on 2023-02-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_robots_fatal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Duracion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Duracion Minutos')),
                ('Proceso', models.TextField(blank=True, null=True)),
                ('Gerencia', models.TextField(blank=True, null=True)),
                ('Server', models.TextField(blank=True, null=True)),
                ('Errores', models.TextField(blank=True, default=0, null=True)),
                ('Warn', models.TextField(blank=True, default=0, null=True)),
                ('Fatal', models.TextField(blank=True, default=0, null=True)),
                ('Estado', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
