# Generated by Django 4.1.4 on 2023-03-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_path_delete_premonitoreo_delete_scanner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='path',
            options={'verbose_name': 'Path', 'verbose_name_plural': 'Path'},
        ),
        migrations.AddField(
            model_name='path',
            name='servidor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='administracion.servidores'),
        ),
    ]
